version: "2"
services:
    mongo:
        image: mongo:3.3
        command: mongod --replSet "test" --smallfiles
        ports:
            - "27017:27017"
    elasticsearch:
        image: elasticsearch:2.3
        command: elasticsearch -Des.network.host=0.0.0.0
        ports:
            - "9200:9200"
            - "9300:9300"
    logstash:
        image: logstash:2.3
        command: logstash -f /etc/logstash/conf.d/logstash.conf
        volumes:
            - ./elk/logstash/config:/etc/logstash/conf.d
        ports:
            - "5000:5000"
        links:
            - elasticsearch        
        depends_on:
            - elasticsearch
    kibana:
        build: elk/kibana/
        volumes:
            - ./elk/kibana/config/:/opt/kibana/config/
        ports:
            - "5601:5601"
        links:
            - elasticsearch
        depends_on:
            - elasticsearch
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
    kafka:
        image: wurstmeister/kafka
        ports:
            - "9092:9092"
        links:
            - zookeeper    
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
            #KAFKA_CREATE_TOPICS: "test:1:1"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            #HOSTNAME_COMMAND: ifconfig docker0 | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'