version: "2"
services:
    web:
        build: .
        links:
            - mongo
            - elasticsearch
            - logstash
        environment:
            - MONGODB_URI=mongodb://mongo:27017/testDb
            - MONGODB_OPLOG_URI=mongodb://mongo:27017/local
            - PORT=2426
        ports:
            - "2426:2426"
        logging:
            driver: gelf
            options:
                gelf-address: "udp://localhost:12201"    
                gelf-tag: "first-logs"
    mongo:
        image: mongo:3.3
        command: mongod --replSet "test" --smallfiles
        ports:
            - "27017:27017"
    elasticsearch:
        image: elasticsearch:2.3
        command: elasticsearch -Des.network.host=0.0.0.0
        ports:
            - "9200:9200"
            - "9300:9300"
    kibana:
        image: kibana:4.5
        links:
            - elasticsearch
        ports:
            - "5601:5601"
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200
# docker run -it --rm logstash logstash -e 'input { stdin { } } output { stdout { } }'
# docker run -it --rm -v "$PWD":/config-dir logstash logstash -f /config-dir/logstash.conf
    logstash:
        image: 'logstash:2.3'
        #command: 'logstash -f /etc/logstash/conf.d/logstash.conf'
        command: "logstash -e 'input { stdin { } } output { stdout { } }'"
        links:
            - elasticsearch
        depends_on:
            - elasticsearch
#        expose:
#            - '5514'
        expose:
            - "12201"
        ports:
            - "12201:12201"
            - "12201:12201/udp"
        restart: on-failure
    logspout:
        image: 'gliderlabs/logspout:v2'
        command: '-c ''/bin/logspout syslog://logstash:12201'''
        entrypoint: /bin/sh
        links:
            - logstash
        depends_on:
            - logstash
        restart: always
        volumes:
            - '/var/run/docker.sock:/tmp/docker.sock'    
#    logstash:
#        image: logstash:2.3
#        command: logstash -f /etc/logstash/conf.d/logstash.conf
#        network_mode: host
#        volumes:
#            - ./logstash.conf:/etc/logstash/conf.d/logstash.conf
#        expose:
#            - "12201"
#        ports:
#            - "12201:12201"
#            - "12201:12201/udp"
#        environment:
#            - ELASTICSEARCH_URL=elasticsearch:9200
#        links:
#            - elasticsearch
