version: "2"
services:
    web:
        build: .
        links:
            - mongo
            - elasticsearch
            - logstash
            - kafka
        environment:
            - MONGODB_URI=mongodb://mongo:27017/testDb
            - MONGODB_OPLOG_URI=mongodb://mongo:27017/local
            - PORT=2426
            - LOGSTASH_HOST=logstash
            - LOGSTASH_PORT=5000
            - STATSD_HOST=statsd
            - STATSD_PORT=8125
            - KAFKA_URI=127.0.0.1:9092
        ports:
            - "2426:2426"
        depends_on:
            - mongo
            - elasticsearch
            - logstash
            - kafka